"""End-to-end healthcare M365 migration walkthrough.

Runs the four phases against the bundled mock healthcare tenant:

    Discovery -> HIPAA gate -> Wave plan -> Post-cutover audit

Emits a single markdown report to `pilot-migration-report.md` in the working
directory that a delivery lead can hand to the practice manager on the day
of the wave-1 cutover.

Run:
    python examples/end_to_end_migration.py

The mock backend ships intentional gaps (unhardened tenant config, MFA
gaps, unlabeled PHI, former staff still licensed) so the report has real
findings to demonstrate.
"""
from __future__ import annotations

from pathlib import Path

from healthcare_m365.backend import get_backend
from healthcare_m365.hipaa_gate import run_hipaa_gate
from healthcare_m365.migration_planner import plan_migration
from healthcare_m365.post_cutover_audit import run_post_cutover_audit


REPORT_PATH = Path("pilot-migration-report.md")


def build_report() -> str:
    backend = get_backend()
    users = backend.list_users()
    config = backend.get_tenant_config()

    gate = run_hipaa_gate(backend)
    plan = plan_migration(backend)
    audit = run_post_cutover_audit(backend)

    parts: list[str] = []
    parts.append("# Pilot migration report")
    parts.append("")
    parts.append("*Generated by the `healthcare-m365-migration` kit against the "
                 "bundled mock tenant. In a real engagement this runs against "
                 "your live tenant via `GRAPH_BACKEND=graph`.*")
    parts.append("")

    parts.append("## 1. Discovery")
    parts.append("")
    parts.append(f"- **Total users:** {len(users)}")
    parts.append(f"- **Departments:** {', '.join(sorted({u.department for u in users}))}")
    parts.append(f"- **License mix:** {_license_mix(users)}")
    parts.append(f"- **Mailboxes to migrate:** {len(backend.list_source_mailboxes())} "
                 f"({sum(m.size_gb for m in backend.list_source_mailboxes()):.1f} GB total)")
    parts.append(f"- **Active accounts:** {sum(1 for u in users if u.account_enabled)}")
    parts.append(f"- **Former accounts (offboard only):** {sum(1 for u in users if u.is_former)}")
    parts.append("")

    parts.append("## 2. HIPAA config gate")
    parts.append("")
    parts.append(f"**{gate.summary()}**")
    parts.append("")
    if gate.blocked:
        parts.append("**Migration is BLOCKED until every FAIL is remediated. "
                     "The delivery lead is responsible for driving remediation "
                     "before Wave 1 goes live.**")
        parts.append("")

    for c in gate.checks:
        marker = {"pass": "PASS", "warn": "WARN", "fail": "FAIL"}[c.status]
        parts.append(f"### [{marker}] {c.name}")
        parts.append(f"*HIPAA citation: {c.hipaa_citation}*")
        parts.append("")
        parts.append(c.detail)
        if c.remediation:
            parts.append("")
            parts.append(f"**Remediation:** {c.remediation}")
        parts.append("")

    parts.append("## 3. Wave plan")
    parts.append("")
    parts.append(f"**{plan.summary()}**")
    parts.append("")
    parts.append("| Wave | Name | Users | Est. hours | Blockers |")
    parts.append("|---|---|---|---|---|")
    for w in plan.waves:
        blockers_str = f"{len(w.blockers)} MFA gap(s)" if w.blockers else "-"
        parts.append(f"| {w.order} | {w.name} | {w.user_count()} | "
                     f"{w.est_hours:.1f} | {blockers_str} |")
    parts.append("")

    for w in plan.waves:
        parts.append(f"### Wave {w.order}: {w.name}")
        parts.append("")
        for u in w.users:
            marker = "  (no MFA)" if not u.mfa_registered and not u.is_former else ""
            parts.append(f"- `{u.display_name}` - {u.department}, {u.job_title}, "
                         f"{u.license_sku}{marker}")
        parts.append("")

    if plan.warnings:
        parts.append("**Planning warnings:**")
        for w in plan.warnings:
            parts.append(f"- {w}")
        parts.append("")

    parts.append("## 4. Post-cutover audit (simulated: Wave 1 completed)")
    parts.append("")
    parts.append(f"**{audit.summary()}**")
    parts.append("")

    if audit.former_still_licensed:
        parts.append(f"### License waste from former staff (${audit.licenses_at_risk_usd:.2f}/mo)")
        parts.append("")
        for u in audit.former_still_licensed:
            parts.append(f"- {u.display_name} - {u.license_sku}")
        parts.append("")
        parts.append("*Action: remove licenses immediately; convert mailbox to shared if legal hold needed.*")
        parts.append("")

    if audit.mfa_gaps:
        parts.append("### MFA gaps (immediate risk)")
        parts.append("")
        for u in audit.mfa_gaps:
            parts.append(f"- {u.display_name} - {u.department}, {u.job_title}")
        parts.append("")

    if audit.stuck_users:
        parts.append("### Users who haven't signed in post-cutover")
        parts.append("")
        for u in audit.stuck_users[:10]:
            parts.append(f"- {u.display_name} - last signin {u.last_signin.date()}")
        if len(audit.stuck_users) > 10:
            parts.append(f"- *(...plus {len(audit.stuck_users) - 10} more)*")
        parts.append("")

    if audit.unlabeled_phi_docs:
        parts.append("### PHI documents without a sensitivity label")
        parts.append("")
        for path in audit.unlabeled_phi_docs:
            parts.append(f"- `{path}`")
        parts.append("")
        parts.append("*Action: run Purview auto-labeling in simulation mode over "
                     "these paths, then enforce.*")
        parts.append("")

    parts.append("---")
    parts.append("")
    parts.append("**Handover checklist:**")
    parts.append("")
    parts.append("- [ ] Every HIPAA FAIL check remediated + verified")
    parts.append("- [ ] Every MFA gap resolved before that user's wave")
    parts.append("- [ ] Former-staff licenses removed")
    parts.append("- [ ] Unlabeled PHI documents auto-labeled")
    parts.append("- [ ] Wave 2 date confirmed with department heads")
    parts.append("- [ ] Rollback playbook signed off (see `docs/customization.md`)")
    parts.append("")

    return "\n".join(parts)


def _license_mix(users: list) -> str:
    counts: dict[str, int] = {}
    for u in users:
        counts[u.license_sku] = counts.get(u.license_sku, 0) + 1
    return ", ".join(f"{sku}={n}" for sku, n in sorted(counts.items()))


def main() -> int:
    report = build_report()
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}  ({len(report.splitlines())} lines)")
    print()
    print("First 40 lines:")
    print()
    for line in report.splitlines()[:40]:
        print(line)
    print()
    print("...")
    print(f"(full report at {REPORT_PATH})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
